#db:
#  username: postgres
#  password: postgres
#  driver: PostgresDriver
#  url: postgres:5432
#  host: localhost, 127.0.0.1
#  pool:
#    size: 12
#    timeout: 10
#    pools:
#      - size: 1
#        timeout: 1
#      - size: 2
#        timeout: 2
#      - size: 3
#        timeout: 3

#spring.profiles.active: qa

#logging:
#  level:
#    root: warn
#    ru.clevertec.console: INFO
#  file:
#    name: poverovLog.log
#    path: /

spring:
#  profiles:
#    active: qa

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
#    driver-class-name: org.postgresql.Driver
#    format-sql: true
#    show-sql: true
#    dialect: org.hibernate.dialect.PostgreSQL9Dialect

#  security:
#    user:
#      name: user-user
#      password: password1234

server:
  port: 8083

#info:
#  name: Spring Data Rest
#  description: This Spring Boot Rest Application is used for CRUD operations with Employees.
#  author: Dzmitry Paverau
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: beans, health, mapping, info